
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Home {
    using System;
    using Terminal.Gui;
    
    
    public partial class BasicView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ListView listview1;
        
        private Terminal.Gui.Button SimpleButton;
        
        private void InitializeComponent() {
            SimpleButton = new Terminal.Gui.Button();
            listview1 = new Terminal.Gui.ListView();
            greenOnBlack = new Terminal.Gui.ColorScheme();
            greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            Width = Dim.Fill(0);
            Height = Dim.Fill(0);
            X = 0;
            Y = 0;
            ColorScheme = greenOnBlack;
            Modal = false;
            Text = "";
            Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            Border.Effect3D = false;
            Border.DrawMarginFrame = true;
            TextAlignment = Terminal.Gui.TextAlignment.Left;
            Title = "My simple UI";
            listview1.Width = 20;
            listview1.Height = 3;
            listview1.X = 73;
            listview1.Y = 4;
            listview1.Data = "listview1";
            listview1.Text = "e";
            listview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            listview1.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item 1",
                        "Item 2",
                        "Item 3"});
            Add(listview1);
            SimpleButton.Width = 13;
            SimpleButton.X = 33;
            SimpleButton.Y = 9;
            SimpleButton.Data = "SimpleButton";
            SimpleButton.Text = "Click Me!";
            SimpleButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            SimpleButton.IsDefault = false;
            Add(SimpleButton);
        }
    }
}
