# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch:
  release:
    branches: master
    type: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Find Latest Tag
      id: find
      uses: oprypin/find-latest-tag@v1.1.1
      with:
       repository: ${{ github.repository }}
       releases-only: true   
       
    - name: Pack
      run: dotnet pack --configuration Release -p:Version=${{ steps.find.outputs.tag }} -p:PackageVersion=${{ steps.find.outputs.tag }} -v m
    
    - name: Publish
      run: dotnet nuget push "/home/runner/work/Frank.Templates/Frank.Templates/bin/Release/Frank.Templates.${{ steps.find.outputs.tag }}.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
