# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  release:
    branches: master
    type: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Find Latest Tag
      uses: oprypin/find-latest-tag@v1.0.4
      with:
       repository: ${{ github.repository }}
       releases-only: true   
    - name: Pack
      run: dotnet pack --configuration Release -p:Version=${{ steps.find.outputs.tag }} -v m
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: "**/Frank.Templates.${{ steps.find.outputs.tag }}.nupkg"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      working-directory: src
      run: dotnet nuget push "**/Frank.Templates.${{ steps.find.outputs.tag }}.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
